steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-ai-agent', '.']
    secretEnv: ['GITHUB_PAT']
secrets:
  - kmsKeyName: projects/YOUR_PROJECT_ID/locations/global/keyRings/YOUR_KEYRING/cryptoKeys/YOUR_KEY
    secretEnv:
      GITHUB_PAT: YOUR_ENCRYPTED_TOKEN
